### ISSUE TITLE
Add MIT open source License

### ISSUE THREAD

**Issue by ankitjain28may** [ankitjain28may/Social-Media-Review-Platform#14]

**Comment by accakks** [comment]
Hi @ankitjain28may  Please review pull request "Created MIT LICENSE #16".
Wrote your name in copyright and year 2017. Will that be okay?

**Comment by ankitjain28may** [comment]
@accakks , Yeah, nice..

**Comment by ankitjain28may** [comment]
@accakks Merged, Thanks for the contribution.
